default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: hackgt-dev

test:
  <<: *default
  database: hackgt-test

production:
  <<: *default
  database: hackgt-prod
